# Generated by Django 5.1.15 on 2026-07-21 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_role'),
        ('purchasing', '0003_backfill_and_alter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_orders', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_suppliers', to='core.organization'),
        ),
    ]
