# Generated by Django 5.1.15 on 2026-07-21 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_default_org'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdebitnote',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoicing_credit_debit_notes', to='core.organization'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='core_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoicing_invoices', to='core.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='core_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoicing_orgs', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tax_id',
            field=models.CharField(max_length=50),
        ),
    ]
