# Generated by Django 5.1.15 on 2026-07-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_role'),
        ('invoicing', '0003_backfill_and_alter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditdebitnote',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoicing_credit_debit_notes', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='core_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoicing_invoices', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='core_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoicing_orgs', to='core.organization'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('core_organization',), name='unique_core_organization_per_invoicing_org'),
        ),
    ]
