# Generated by Django 5.1.15 on 2026-07-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_default_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
