# Generated by Django 5.1.15 on 2026-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fiscal_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_regime',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('simplified', 'Simplified'), ('special', 'Special'), ('exempt', 'Exempt')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Designates this member as an organization owner.'),
        ),
    ]
