# Generated by Django 5.1.15 on 2026-07-21 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_is_owner_and_fiscal_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(choices=[('product', 'Product'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('organization', 'Organization')], help_text='Target model for this custom field.', max_length=50)),
                ('name', models.CharField(help_text='Display name for the field (e.g. "SKU", "RFC").', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select')], help_text='Determines input rendering and validation.', max_length=20)),
                ('required', models.BooleanField(default=False, help_text='If True, the field blocks create/update when empty.')),
                ('options', models.JSONField(blank=True, help_text='For select fields: list of valid choices, e.g. ["S","M","L"].', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (ascending), ties resolved by name.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='core.organization')),
            ],
            options={
                'ordering': ['organization', 'model_name', 'order', 'name'],
                'unique_together': {('organization', 'model_name', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('product', 'Product'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('organization', 'Organization')], help_text='Model type of the entity this value belongs to.', max_length=50)),
                ('entity_id', models.UUIDField(help_text='UUID of the entity instance.')),
                ('value', models.TextField(blank=True, default='', help_text='Stored as text; cast by the mixin on read (e.g. number, date).')),
                ('field', models.ForeignKey(help_text='The field definition this value corresponds to.', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.customfield')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='core.organization')),
            ],
            options={
                'ordering': ['field__order', 'field__name'],
                'unique_together': {('entity_type', 'entity_id', 'field')},
            },
        ),
    ]
