# Generated by Django 5.1.15 on 2026-07-21 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.CharField(choices=[('sales_order', 'Sales Order'), ('purchase_order', 'Purchase Order')], help_text='Which order type this rule gates.', max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Orders with total >= this amount require approval.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('approver_role', models.ForeignKey(blank=True, help_text='Members holding this role may approve/reject.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_rules', to='core.role')),
                ('approver_users', models.ManyToManyField(blank=True, help_text='Individually authorized approvers, in addition to role holders.', related_name='approval_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='core.organization')),
            ],
            options={
                'ordering': ['organization', 'order_type'],
                'unique_together': {('organization', 'order_type')},
            },
        ),
    ]
