# Generated by Django 5.1.15 on 2026-07-21 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_approval_rule'),
        ('inventory', '0005_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrule',
            name='min_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Orders whose (product-scoped or total) quantity >= this require approval.', null=True),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='product',
            field=models.ForeignKey(blank=True, help_text='If set, rule only applies to orders containing this product.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules', to='inventory.product'),
        ),
    ]
