# Generated by Django 5.1.15 on 2026-07-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_approvalrule_min_quantity_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrule',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Orders with total >= this amount require approval.', max_digits=12, null=True),
        ),
    ]
